### ISSUE TITLE
[question] iati-data-jump vs bulk-data-service

### ISSUE THREAD

**Issue by siemvaessen** [IATI/bulk-data-service#19]
Just a quick question: will the bulk-data-service act similar to [iati-data-dump](https://github.com/codeforIATI/iati-data-dump)?

**Comment by robredpath** [comment]
Yes, they are similar. Both tools go through the process of getting a list of URLs to download from the Registry, downloading the linked files, creating a .zip archive of the results, and making it available for download. 

There are a few key differences. The Bulk Data Service stores far more information about what happened during the download process, to help with debugging, whereas IATI Data Dump only stores an error code. It also generates hashes to help consuming applications detect whether specific files have changed; the Data Dump replicates the hashes from the Registry but there's no guarantee that the file that the Registry hashed is the same as the file that the Data Dump downloaded. 

IATI Data Dump stores a lot of data from the Registry, whereas the Bulk Data Service only stores a minimal set of metadata. 

Hope that helps @siemvaessen - do let me know if you have any further questions.

**Comment by robredpath** [comment]
> This is production(/ready) and running as an IATI service?

It's been soft-launched at https://bulk-data.iatistandard.org - it's running, but we want to do more work on the website before we publicise it at all, and we're monitoring it in use to understand how it performs and where any unexpected issues might arise from. We're also working through some questions about what goes into the download file, so we don't really want people to build on it just it. 

The main purpose of this development is to provide a source for the various data tools that the Secretariat maintains; it largely replaces an existing component that was integrated into the pipeline that we wanted to improve. As part of trying to minimise variance between Secretariat tools, we're trying to make it so that the source data that's loaded into the tools is as similar as possible and updated close to real-time. 

Once we'd made it, it was pretty easy to make this a service that was available for anyone to use, so we did. 

> Am I correct in understanding that IATI Data Dump stores "more" 

I think these are the headline differences:

| Data Dump | Bulk Data Service |
| --- | --- |
| All the data from publishers | All the data from publishers |
| A fairly complete dump of the Registry | Just the publisher name from the Registry |
| File hashes from the Registry | File hashes generated at download time |
| Minimal download session information | Substantial download session information |
| Runs once a day | Runs multiple times per day |

**Comment by simon-20** [comment]
Hi @siemvaessen,

Here is an example of what the Bulk Data Service stores during a failed download process. In this case, the file is being blocked by Cloudflare, so the Bulk Data Service application can't access it:

```json
      "download_error_details": {
        "bds_message": "Download of IATI XML failed with non-200 HTTP status",
        "http_headers": {
          "Accept-CH": "Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA",
          "CF-RAY": "8c91dac1394b7771-LHR",
          "Cache-Control": "private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
          "Connection": "close",
          "Content-Encoding": "gzip",
          "Content-Type": "text/html; charset=UTF-8",
          "Critical-CH": "Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA",
          "Cross-Origin-Embedder-Policy": "require-corp",
          "Cross-Origin-Opener-Policy": "same-origin",
          "Cross-Origin-Resource-Policy": "same-origin",
          "Date": "Thu, 26 Sep 2024 08:23:53 GMT",
          "Expires": "Thu, 01 Jan 1970 00:00:01 GMT",
          "Origin-Agent-Cluster": "?1",
          "Permissions-Policy": "accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()",
          "Referrer-Policy": "same-origin",
          "Server": "cloudflare",
          "Strict-Transport-Security": "max-age=15552000; preload",
          "Transfer-Encoding": "chunked",
          "Vary": "Accept-Encoding",
          "X-Content-Options": "nosniff",
          "X-Content-Type-Options": "nosniff",
          "X-Frame-Options": "SAMEORIGIN",
          "alt-svc": "h3=\":443\"; ma=86400",
          "cf-chl-out": "Rz3KpsQpa8ikXR0m59z13rsdH5ymybZro/NaGyrquc4Qz54h2Ar2NMyEy0hjr62WoMpDF9M63BnGIUPBRsg+2/YTI8h/kNiculsDTi2mSEioI3L7DaPSWyCruwp39SAlUhfccu2BUl9xAg/Bq6hNBw==$FBaPvLnwnJ+vRZDyFItLXA==",
          "cf-mitigated": "challenge"
        },
        "http_method": "GET",
        "http_reason": "Forbidden",
        "http_status_code": 403,
        "message": "HTTP GET request failed with non-200 status",
        "url": "https://www.ifrc.org/Docs/IATI%20Publications/IATI_activity_202209.xml"
      },
```

This, we hope, is going to be useful information for the Secretariat tooling, and potentially others too, and should make it easier to diagnose problems with inaccessible datasets.

**Comment by siemvaessen** [comment]
Thanks @robredpath and @simon-20 for the elaborate update and explanation.
